[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "tesseract", "ffmpeg"]

[phases.install]
cmds = ["pip install SpeechRecognition PyMuPDF Pillow"]

[phases.build]
cmds = ["go build -o main ."]

[start]
cmd = "./main"
